### ISSUE TITLE
Android Messenger stops responding when not connected.

### ISSUE THREAD

**Issue by Ben496** [Ben496/Bluetooth-Messenger#24]
Android Messenger stops responding when a new message is received while not connected to a pc.

**Comment by HoneaRyan** [comment]
I think when it receives a message, the broadcast receiver is assigned to send it that way. Probably need to specify for it not to be listening if no connection or something along those lines.

**Comment by Ben496** [comment]
Yeah, I'll just check if it's connected before trying to send it. When I get around to doing that.

**Comment by Ben496** [comment]
Fixed by checking if connected before trying to send the received message to the PC. See commit 73b38864a9ae1131d6099e0c5151a177b7f592fa
